name: Wheel Builder
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to build
  # Do not add any non-tag push events without updating pypi-publish.yml. If
  # you do, it'll upload wheels to PyPI.
  push:
    tags:
      - '*.*'
      - '*.*.*'
  pull_request:
    paths:
      - .github/workflows/wheel-builder.yml

jobs:
  sdist:
    runs-on: ubuntu-latest
    name: Build Python 3 wheels
    steps:
      - uses: actions/checkout@v3
        with:
          # The tag to build or the tag received by the tag event
          ref: ${{ github.event.inputs.version || github.ref }}
          persist-credentials: false

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build wheels
        run: |
          python -m pip install setuptools wheel
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: ./dist/*.whl
          overwrite: true